export = createError

declare function createError (
  code: string,
  message: string,
  statusCode?: number,
  Base?: Error
): createError.FastifyErrorConstructor

declare namespace createError {
  interface FastifyError extends Error {
    code: string;
    name: string;
    statusCode?: number;

    toRFC7807: (instance?: RFC7807Error['instance'], details?: RFC7807Error['details']) => RFC7807Error;
  }

  interface RFC7807Error {
    /**
     * A URI reference [RFC3986] that identifies the
     * problem type.  This specification encourages that, when
     * dereferenced, it provide human-readable documentation for the
     * problem type (e.g., using HTML [W3C.REC-html5-20141028]).
     * When this member is not present, its value is assumed to be
     * "about:blank".
     */
    type: string;
    /**
     * A short, human-readable summary of the problem
     * type.  It SHOULD NOT change from occurrence to occurrence of the
     * problem, except for purposes of localization (e.g., using
     * proactive content negotiation; see [RFC7231], Section 3.4).
     */
    title: string;
    /**
     * The HTTP status code ([RFC7231], Section 6)
     * generated by the origin server for this occurrence of the problem.
     */
    status: number;
    /**
     * A human-readable explanation specific to this
     * occurrence of the problem.
     */
    detail: string;
    /**
     * A URI reference that identifies the specific
     * occurrence of the problem. It may or may not yield further
     * information if dereferenced.
     */
    instance: string;
    code: string;
    details: { [key: string]: any };
  }

  interface FastifyErrorConstructor {
    new(a?: any, b?: any, c?: any): FastifyError;
    (a?: any, b?: any, c?: any): FastifyError;
    readonly prototype: FastifyError;
  }
}
